### ISSUE TITLE
no joke, I was about to publish this last night lol

### ISSUE THREAD

**Issue by jonschlinkert** [wooorm/profanities#1]
On my life I had the package put together and you beat me to it lol! I'll just use this one now. 

I was going to do it a bit differently though. I exposed methods for getting specific words, like the 7 most common cuss words is exposed on the `.carlin` property. or if you want a list of common, non-cuss words that still manage to offend people, you can get the list from the `.jonschlinkert` property.

Seriously though, stop reading my mind!  (feel free to close, just wanted to stop by. nice work!)

**Comment by wooorm** [comment]
hahaha, how funny! Although, the first commit is from [14 September, 2014](https://github.com/wooorm/profanities/commit/2a501ab6a91beb4f0afd07f00a3d22e2140c00af), I only now came to using it and releasing 1.0.0 :wink: (in a few minutes I’m pushing retext-profanities).

Now, there’s of course still room for such categorisation, though perhaps in something named other than `profanities`. I also have the idea of “rating” words in the “level of vulgarity”. E.g., `butt` isn’t *that* bad.
[Some other’s aren’t either](https://github.com/wooorm/profanities/blob/8cc7dfc2ddac1f6c86b26091ae4d222c1bb34c7a/script/build-data.js#L29-L39). Maybe in the future!

Thanks for reaching out, great story! :laughing:

**Comment by jonschlinkert** [comment]
> I only now came to using it and releasing 1.0.0  (in a few minutes I’m pushing retext-profanities).

ohh... I see now (says the blind man). thanks for pointing that out. I would have probably found it anyway though, you have some great language-related libs!

**Comment by wooorm** [comment]
Yeah probably :wink: Thanks a lot Jon!
